services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
