# Generated by Django 5.0.2 on 2024-04-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
